services:
  api:
    build:
      context: ./api
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - ./.env 

  react:
    depends_on:
      - api
    build:
      context: ./react
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    env_file:
      - ./.env 
    volumes:
      - ./react/src:/app/src:z
